### ISSUE TITLE
How to identify which servers are up?

### ISSUE THREAD

**Issue by savins93** [Sistemas-Multimedia/Icecast-tracker#2]
I have tried to do ping but I cant. And the problem is that if my application try to download status2.xsl and the server doesn't exist, it crashes. 

I used this solution to ping:
http://stackoverflow.com/questions/2953462/pinging-servers-in-python

**Comment by vicente-gonzalez-ruiz** [comment]
Hi Savins,

(as you probably knows) it is possible to can capture the exception produced by the no-existence of the server and treat it (sending a warning to the terminal and trying with the following sever).

Anyway, where is the code (please, file and lines) where you do this?

Regards,
Vi.

**Comment by savins93** [comment]
I've been testing the BBB-1080HD video for half an hour and you have deleted it from the server.
Thank you very much :-1:

**Comment by savins93** [comment]
I have already solved the problem with file status2.xsl. The source code is available in `Icecast-tracker/Django/Savins/Icecast_tracker/Icecast_tracker_app/views.py`
https://github.com/Sistemas-Multimedia/Icecast-tracker/blob/master/Django/Savins/Icecast_tracker/Icecast_tracker_app/views.py

The first method show all the channel in database and the second search the best server to serve the source.

**Comment by vicente-gonzalez-ruiz** [comment]
Sorry Savins, I did suppose that none of you were using this video. For the sake of curiosity, how did you know I "deleted" the video? 

Anyway there is a reason why I disabled the feeding of this high bit-rate video. When a Icecast relay server has to retransmit the videos and there is not enough capacity in the link, the relayed videos are selected at random. I though that disabling BBB-1080 I had making your work easier :-/

Sorry again.

Vi.

**Comment by savins93** [comment]
Don't worry XD.
The 1080HD video was the first channel that I added to my database. I  have always tested with this video and  the song of tempura, but now I have changed it.

Answering your question, I added a false second server to verify that my program chooses the one server that it was active . For that I added a try catch block.
(Now it's better watch the code for understanding my problem): 
https://github.com/Sistemas-Multimedia/Icecast-tracker/blob/master/Django/Savins/Icecast_tracker/Icecast_tracker_app/views.py
 
So, I thought that when the exception  jumped, the value of the variables are lost. Then I went up to my method by print until you reach the most basic thing. The status2.xsl downloaded in this moment from the server. Then I watched that  the number of sources were less. And that's when I discovered that there were only three channels.
And that's it.

I need to make the project readme.md but while if you want to test, you can download it and in the directory where is manage.py, launches the command `python manage.py runserver` and it is deplayed on port 8000. the database is in repository too, so you can try it directly.

The dislike was a foolishness, i wrote ":" because I wanted to write :( but then the hand appears so I put it.

**Comment by vicente-gonzalez-ruiz** [comment]
Hi Savins,

I am not sure whether you solved your issue "How to know if a server is up?".

What I would do is to try to establish a TCP connection with it. If the connection is successful, the server is alive.

Regards,
Vi.

**Comment by savins93** [comment]
Hi Vicente,
I have solved the problem in my code with:
`if urllib2.urlopen(icecastServer+"/status2.xsl").getcode() == 200:`

I understand that if response is code 200, the server is running. if I get other code, the server doesn't work.

Regards,
Savíns.
